version: '3'


services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - main

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    networks:
      - main
    ports:
      - "3000:5672"
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - main
    ports:
      - '4000:5432'
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery_worker:
    build: .
    container_name: celery_worker
    command: "celery -A config worker --loglevel=INFO"
    depends_on:
      - app
      - rabbitmq
      - postgres
    environment:
      - C_FORCE_ROOT="true"
    networks:
      - main
    restart: on-failure
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_file:/app/static
      - media_file:/app/media
    restart: always
    ports:
      - "8000:8000"
    container_name: app
    command: sh -c 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - rabbitmq
      - postgres
      - redis


networks:
  main:
    external: true
    
    
volumes:
  postgres_data:
    external: true

  static_file:
    external: true
  
  media_file:
    external: true