# Generated by Django 3.2.7 on 2021-09-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210919_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLanguageField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('lang', models.CharField(choices=[('en', 'english'), ('fa', 'persian'), ('ar', 'arabic')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name',
        ),
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.ManyToManyField(to='product.MultiLanguageField'),
        ),
    ]
