# Generated by Django 3.2.7 on 2021-09-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210919_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiLanguageField',
            new_name='BrandMultiLanguage',
        ),
    ]
