# Generated by Django 3.2.7 on 2021-09-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_multilanguagefield_brandmultilanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
