# Generated by Django 3.2.7 on 2021-09-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_auto_20210923_2148'),
        ('product', '0009_auto_20210919_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.discount'),
        ),
    ]
