# Generated by Django 3.2.7 on 2021-09-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210923_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='after_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
