# Generated by Django 3.2.7 on 2021-09-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_after_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='after_discount_price',
        ),
    ]
