# Generated by Django 3.2.7 on 2021-09-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='product.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='meta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
