# Generated by Django 3.2.7 on 2021-09-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20210923_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
