# Generated by Django 3.2.7 on 2021-09-23 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_alter_discount_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount',
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
