# Generated by Django 3.2.7 on 2021-09-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_discount_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='condition',
            field=models.CharField(choices=[('t', 'TIMELY'), ('f', 'FIRST_ORDER'), ('p', 'PERCENTAGE')], max_length=1),
        ),
    ]
