# Generated by Django 3.2.7 on 2021-09-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210915_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
    ]
