# Generated by Django 3.2.7 on 2021-09-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True, verbose_name='price'),
        ),
    ]
