# Generated by Django 3.2.7 on 2021-09-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_auto_20210923_2148'),
        ('cart', '0004_alter_item_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount', to='discount.discount'),
        ),
    ]
