# Generated by Django 3.2.7 on 2021-09-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_cart_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
