# Generated by Django 3.2.7 on 2021-09-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart_items',
            new_name='items',
        ),
    ]
