# Generated by Django 3.2.7 on 2021-09-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_item_price'),
        ('order', '0005_rename_cart_items_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='cart.Item'),
        ),
    ]
