# Generated by Django 3.2.7 on 2021-09-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210926_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='after_discount_price',
        ),
    ]
